services:
  cache-proxy-1:
    image: devmaksdev/nginx-reverse-proxy-cache:amd64
    container_name: cache-proxy-1
    environment:
      S3_BUCKET_NAME: www.my.githubresumebuilder.cloud.s3-website-us-east-1.amazonaws.com
    ports:
      - "8081:80"
    restart: always
  
  cache-proxy-2:
    image: devmaksdev/nginx-reverse-proxy-cache:amd64
    container_name: cache-proxy-2
    environment:
      S3_BUCKET_NAME: www.my.githubresumebuilder.cloud.s3-website-us-east-1.amazonaws.com
    ports:
      - "8082:80"
    restart: always
  
  cdn-lb:
    image: devmaksdev/cdn-least-con-lb-image:latest
    container_name: cdn-lb
    environment:
      - CACHE_SERVERS=server cache-proxy-1; server cache-proxy-2;
    ports:
      - "80:80"
    depends_on:
      - cache-proxy-1
      - cache-proxy-2
    restart: always